# -- Global values shared across all subcharts.
global:
  image:
    registry: ""
    tag: "latest"
    pullPolicy: IfNotPresent
  aws:
    region: eu-west-2
    account: ""

# -- Producer subchart overrides.
producer:
  enabled: true

# -- Consumer subchart overrides.
consumer:
  enabled: true

# -- API subchart overrides.
api:
  enabled: true
