// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.1
// source: proto/weather_chat.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeatherChat_Chat_FullMethodName = "/hello.WeatherChat/Chat"
)

// WeatherChatClient is the client API for WeatherChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for handling Weather Chat
type WeatherChatClient interface {
	// Chat sends a message and receives a weather chat response.
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, ChatResponse], error)
}

type weatherChatClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherChatClient(cc grpc.ClientConnInterface) WeatherChatClient {
	return &weatherChatClient{cc}
}

func (c *weatherChatClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WeatherChat_ServiceDesc.Streams[0], WeatherChat_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WeatherChat_ChatClient = grpc.BidiStreamingClient[ChatRequest, ChatResponse]

// WeatherChatServer is the server API for WeatherChat service.
// All implementations must embed UnimplementedWeatherChatServer
// for forward compatibility.
//
// Service for handling Weather Chat
type WeatherChatServer interface {
	// Chat sends a message and receives a weather chat response.
	Chat(grpc.BidiStreamingServer[ChatRequest, ChatResponse]) error
	mustEmbedUnimplementedWeatherChatServer()
}

// UnimplementedWeatherChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeatherChatServer struct{}

func (UnimplementedWeatherChatServer) Chat(grpc.BidiStreamingServer[ChatRequest, ChatResponse]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedWeatherChatServer) mustEmbedUnimplementedWeatherChatServer() {}
func (UnimplementedWeatherChatServer) testEmbeddedByValue()                     {}

// UnsafeWeatherChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherChatServer will
// result in compilation errors.
type UnsafeWeatherChatServer interface {
	mustEmbedUnimplementedWeatherChatServer()
}

func RegisterWeatherChatServer(s grpc.ServiceRegistrar, srv WeatherChatServer) {
	// If the following call panics, it indicates UnimplementedWeatherChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeatherChat_ServiceDesc, srv)
}

func _WeatherChat_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WeatherChatServer).Chat(&grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WeatherChat_ChatServer = grpc.BidiStreamingServer[ChatRequest, ChatResponse]

// WeatherChat_ServiceDesc is the grpc.ServiceDesc for WeatherChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.WeatherChat",
	HandlerType: (*WeatherChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _WeatherChat_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/weather_chat.proto",
}
